-- +goose Up
-- +goose StatementBegin

CREATE TYPE job_status AS ENUM (
    'PENDING',
    'SCHEDULED',
    'RUNNING',
    'SUCCEEDED',
    'FAILED'
);

-- failure_reason is a free-text field, but in practice the controller only
-- ever writes one of the customer-facing messages from the REQ-4.1 mapping
-- table. Documented here so everyone agrees on the canonical strings before
-- the controller and API are both writing/reading them:
--
--   oom               -> "Your job ran out of memory. Try requesting more memory or reducing batch size."
--   node_failure      -> "A hardware issue interrupted your job. This is not a problem with your code — please resubmit."
--   nonzero_exit      -> "Your job exited with an error. Check the logs for the full traceback."
--   scheduling_timeout -> "No GPUs of the requested type were available within the timeout window. Please try again or contact support."
--   build_failure     -> "We could not install your dependencies. Check that your requirements file is valid and all packages exist."
--
-- Note: pre-submission script validation (syntax errors etc.) happens
-- synchronously inside POST /jobs, before a row is ever created. That
-- failure path returns a 422 with its own error code (e.g.
-- script_syntax_error) documented in API_CONTRACT.md, and intentionally
-- does NOT live in this enum — failure_code is only for jobs that were
-- successfully created and later failed.
--
-- We store BOTH a short machine-readable code (failure_code) and the
-- human-readable message (failure_reason) so the API doesn't have to
-- re-derive the message, and so future clients (web UI, SDK) can branch
-- on the code without parsing English text.
CREATE TYPE failure_code AS ENUM (
    'oom',
    'node_failure',
    'nonzero_exit',
    'scheduling_timeout',
    'build_failure'
);

CREATE TABLE jobs (
    id              TEXT PRIMARY KEY,          -- e.g. 'job-8f3a2c1d', generated by the API on submission
    customer_id     TEXT NOT NULL,             -- placeholder for multi-tenancy; sent via X-Customer-Id header, trusted as-is until auth exists

    status          job_status NOT NULL DEFAULT 'PENDING',
    status_message  TEXT,                      -- human-readable current-state message, e.g. "Your job is running on 2 x A100 GPUs."

    -- submission inputs (REQ-1.1 / REQ-2.1 / REQ-3.1)
    artifact_location TEXT NOT NULL,           -- MinIO object key the script was uploaded to via presigned PUT (see POST /jobs/presign). Not the script content itself.
    requirements_spec TEXT,                    -- raw contents of requirements.txt / pyproject.toml, or a storage key
    python_version  TEXT NOT NULL,
    gpu_type        TEXT NOT NULL,
    gpu_count       INTEGER NOT NULL CHECK (gpu_count > 0),

    -- failure detail (REQ-4.1)
    failure_code    failure_code,
    failure_reason  TEXT,                      -- rendered human-readable message; NULL unless status = 'FAILED'

    -- retention (REQ-1.2)
    retention_period_days INTEGER NOT NULL DEFAULT 7,

    -- timestamps (REQ-4.1 response shape) — all UTC, ISO 8601 with Z suffix at the API layer
    submitted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Supports "give me all FAILED jobs in the last 7 days" and the GC sweep query
CREATE INDEX idx_jobs_status ON jobs (status);
CREATE INDEX idx_jobs_created_at ON jobs (created_at);
CREATE INDEX idx_jobs_customer_id ON jobs (customer_id);

-- Supports the scheduling-timeout watcher: "all PENDING/SCHEDULED jobs older than N minutes"
CREATE INDEX idx_jobs_status_submitted_at ON jobs (status, submitted_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS jobs;
DROP TYPE IF EXISTS failure_code;
DROP TYPE IF EXISTS job_status;

-- +goose StatementEnd
